# PRODUCTION

version: "3.7"

services:
  node:
    container_name: node
    image: ponomarevandrey/node-docker-deploy
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - ./node/.env
